# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Flatten the curve
email: hello@flattenthecurve.com
description: >- # this means to ignore newlines until "baseurl:"
  These guidelines are intended to help Flatten the Curve with the COVID19 outbreak,
  to help limit spread and reduce the load on hospitals and other healthcare.
baseurl: "" # the subpath of your site, e.g. /blog
url: https://www.flattenthecurve.com
twitter_username: FlattenCurve
github_username:  flattenthecurve

destination: build # required for github publish workflow

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-toc
  - jekyll-polyglot
  - jekyll-twitter-plugin
  # - jekyll-feed

include:
  - images/*.svg

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - docker-compose.yml
  - docker-compose.*.yml
  - README.md
  - import-translations.sh
  - import_language.rb
  - build

languages: ['en', 'es', 'de', 'fr', 'it', 'el']
default_lang: 'en'
exclude_from_localization: ['assets', 'css', 'build']
parallel_localization: false
google_analytics: UA-160096348-1

collections:
   resources:
    resource: true
    sort_by: country
